// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the non-pooling (direct) URL for migrations — required when the
    // runtime URL goes through a pooler (Supabase PgBouncer / Vercel Postgres).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
